### ISSUE TITLE
Website link?

### ISSUE THREAD

**Issue by sbonaretti** [incognia/Juno#15]
Hey, thanks so much for doing all this! Would it make sense to add a link to the website (https://learnpythonwithjupyter.com/) in the readme file, so that people can also get the book? What do you think? Thanks again :)

**Comment by incognia** [comment]
Of course, I haven't had the time to draft the README.md yet, which is why I haven't included it, but I do plan to add it. Thank you very much for the suggestion and your interest.

**Comment by incognia** [comment]
Done:

https://github.com/incognia/Juno#acknowledgments

**Comment by sbonaretti** [comment]
Wow, this is why more I would have ever expected! Thanks so much for everything! I am going to add this project to the book webpage as well in the coming days!

**Comment by incognia** [comment]
I want to say, on the contrary, I am in debt and appreciate that you take the time to review my project and respond.

As a side note, I want to point out that I have taken care to comment my code in detail, but the comments are in Spanish since my students are young, aged 12 to 15, from Mexico City, and some of them do not speak English. However, the project's README is in English.

**Comment by incognia** [comment]
Serena, besides the acknowledgments section, I also give mention to you and your project in the introduction and a couple more times throughout the README.md. I think I can consider this ISSUE closed successfully if it suits you.
